### PR TITLE
Fixes titles

### PR DESCRIPTION
**Pull request by Rafase282**
This just fixes the markdown a little bit.

### CODE REVIEW

**Comment by Cellule** [comment]
Thanks

**Comment by Rafase282** [comment]
No problem, I'm working on a project where I take strings and want to turn them into arguments so I found your package, but i also need to implement something like [command-line-args](https://github.com/75lb/command-line-args). 

Are you by any chance working something similar?

**Comment by Cellule** [comment]
I honestly don't recommend implementing your own command line parser since it's a problem that has been done many times over by now.
My favorite one it http://yargs.js.org/ which you can pass an array of arguments or a string directly with [yargs.parse(args [,context, callback])](http://yargs.js.org/docs/#methods-parseargs-context-parsecallback)
I don't intend to work on a command line parser anytime soon.

**Comment by Rafase282** [comment]
It is not what I'm trying to do. I have a bot where the user provides input via a keyword. So I want to be able to use the command line arguments style with it. With your package I split the string into the right parts and then use it as I would with a regular command line arguments but instead, the options will tell me what functions to run.

So the user does not really have a command line, the closest thing would be the chat but the app would already be running.

https://github.com/Rafase282/SlackNPodio

**Comment by Cellule** [comment]
I still think yargs could be useful to your case since it doesn't need to use `process.argv`.
If you look at the second example in yargs it sounds exactly like your use case ie:
```js
// providing the `fn` argument to `parse()` runs yargs in headless mode, this
// makes it easy to use yargs in contexts other than the CLI, e.g., writing
// a chat-bot.
```

**Comment by Rafase282** [comment]
Thank you, I found [it](https://github.com/yargs/yargs/#parseargs-context-parsecallback). I'll have to study it a bit but it seems like it really does what I want.

It will save me a lot of trouble as I didn't really want to implement the whole thing unless there really was nothing like that out there. It might even help me setup configurations for running the bot itself to allow me to enable and disable features. That is something I haven't done ever yet I see many apps where you can specify the envirioment.

**Pull request merged**
