### PR TITLE
Dependency Fix - Nested Quotes - `--key="value"` format

### LINKED ISSUE #2: Doesn't correctly handle nested quotes
### test.js

```javascript
let parseArgv = require('string-argv').parseArgsStringToArgv;
let string = `--title "Peter's Friends" --name 'Phil "The Power" Taylor'`;

console.log(parseArgv(string));
```
### expect
```javascript
[ "--title", "Peter's Friends", "--name", 'Phil "The Power" Taylor' ]
```

### get

```javascript
[ "--title", "Peter", "s", "Friends", " --name ", "Phil", "The Power", "Taylor" ]
```

### PR DESCRIPTION
**Pull request by Cellule**
This is a pull request combining #1 and #3 (Thanks to @chocolateboy and @gliviu)
Closes #1
Fixes #2
Closes #3 

I combined both changes and added another format `--key="some value"`
I updated the documentation accordingly.
I combined all these changes because this project doesn't seem to be maintained.

I wanted a valid project to do my work, so I can do `npm install cellule/string-argv --save`
If this gets merged, I would love to be able to install from npm again.
If it doesn't get merged after a while, I might fork it and publish to npm under a different name (there is no license in the project so it's hard to tell if I can do this or not #4)

[Review on Reviewable](https://reviewable.io/reviews/mccormicka/string-argv/5)

### CODE REVIEW

**Comment by mccormicka** [comment]
Hi @Cellule,
I am unable to continue maintaining this project. 
However I am happy to set you up as a contributor and give you access to publish to NPM.

Let me know.

**Comment by Cellule** [comment]
Since the scope of the project is fairly small, I don't mind taking over

**Comment by mccormicka** [comment]
@Cellule I have added you as a contributor so you can now merge Pull Requests and maintain this repository. I tried to add you as an owner on NPM but I could not find your username. Can you ping me your NPM details and i will set it up so you can push updates to NPM for this repo.

Happy Coding.

**Comment by Cellule** [comment]
@mccormicka You can find my npm profile at https://www.npmjs.com/~cellule

**Comment by Cellule** [comment]
I will merge this for the time being and once you have some time to add me to publish on npm I will update the package

**Comment by mccormicka** [comment]
@Cellule You are now added as one of the owners of the package and can publish to npm

**Pull request merged**
